const GAME=window.MYBETS_GAME;
const $=id=>document.getElementById(id);
const money=v=>Number(v||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
let config=null,account=null,bet=1,spinning=false;
async function api(url,options={}){const r=await fetch(url,{credentials:"same-origin",cache:"no-store",...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Erro na operação.");return d}
function draw(grid){$("reels").innerHTML=grid.map(s=>'<div class="reel" data-id="'+s.id+'">'+s.label+"</div>").join("")}
function initial(){const symbols=config.symbols,n=config.rows*config.columns;draw(Array.from({length:n},(_,i)=>symbols[i%symbols.length]))}
async function load(){try{const c=await api("/api/games/"+GAME.id+"/config"),a=await api("/api/account");config=c.game;account=a.account;bet=Math.max(config.minBet,1);$("balance").textContent="R$ "+money(account.available_balance);$("bet").textContent=money(bet);initial()}catch(e){$("result").textContent=e.message||"Faça login para jogar.";$("spin").disabled=true}}
function changeBet(delta){if(!config||spinning)return;bet=Math.min(config.maxBet,Math.max(config.minBet,Number((bet+delta).toFixed(2))));$("bet").textContent=money(bet)}
async function animate(){let t=0;return new Promise(resolve=>{const timer=setInterval(()=>{const n=config.rows*config.columns;draw(Array.from({length:n},()=>config.symbols[Math.floor(Math.random()*config.symbols.length)]));document.querySelectorAll(".reel").forEach(x=>x.classList.add("spinfx"));if(++t>=16){clearInterval(timer);resolve()}},55)})}
async function spin(){if(spinning||!config)return;spinning=true;$("spin").disabled=true;$("minus").disabled=true;$("plus").disabled=true;$("result").className="result";$("result").textContent="Girando...";await animate();try{const d=await api("/api/games/"+GAME.id+"/spin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({betAmount:bet})});account=d.user;$("balance").textContent="R$ "+money(account.availableBalance);draw(d.spin.grid);if(d.spin.won){document.querySelectorAll('.reel[data-id="'+CSS.escape(d.spin.winningSymbol)+'"]').forEach(x=>x.classList.add("win"));$("result").className="result win";$("result").textContent="PRÊMIO: R$ "+money(d.spin.prize)+" · "+d.spin.multiplier+"x"}else{$("result").textContent="Não foi dessa vez."}}catch(e){$("result").textContent=e.message||"Erro ao jogar."}finally{spinning=false;$("spin").disabled=false;$("minus").disabled=false;$("plus").disabled=false}}
$("minus").onclick=()=>changeBet(-1);$("plus").onclick=()=>changeBet(1);$("spin").onclick=spin;load();